trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}

jobs:
  - job: continuous_delivery
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.8'
        displayName: '🧪 Usando Python 3.8'

      - script: |
          echo "{}" > ~/.databricks-connect
        displayName: '⚙️ Databricks config'

      - script: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt wheel twine databricks-cli great_expectations
        displayName: '📦 Instalando dependências'

      - script: |
          python setup.py bdist_wheel
        displayName: '🛠️ Gerando pacote'

      - task: TwineAuthenticate@1
        inputs:
          artifactFeed: 'python_library_teste'
        displayName: '🔐 Autenticando no Feed'

      - script: |
          twine upload -r "python_library_teste" --config-file $(PYPIRC_PATH) dist/*
        displayName: '📤 Upload do pacote'

      - name: 🧪 Validar schema com Great Expectations
        run: |
          great_expectations checkpoint run iris_validation_checkpoint || exit 1
        displayName: '✅ Validando dados com Great Expectations'

      - name: 📦 Validar Asset Bundle
        run: databricks bundle validate
        displayName: '📋 Validando Bundle'

      - name: 🚀 Deploy Bundle para Databricks
        run: databricks bundle deploy --target dev
        displayName: '🚀 Deploy Bundle'

      - name: 🧪 Executar pipeline de testes
        run: databricks bundle run test_pipeline --target dev
        displayName: '🔁 Rodando test_pipeline com dados mockados'

      - name: 🧠 Executar pipeline principal (iris_pipeline)
        run: databricks bundle run iris_pipeline --target dev
        displayName: '🌈 Executando pipeline oficial'

      - name: ✅ Notificar sucesso no Teams
        if: success()
        run: |
          curl -H 'Content-Type: application/json' -d '{
            "title": "✅ CD Pipeline",
            "text": "Deploy do bundle e execução dos pipelines realizados com sucesso! 🎉"
          }' $TEAMS_WEBHOOK_URL
        displayName: '📣 Notificar Teams (sucesso)'

      - name: ❌ Notificar falha no Teams
        if: failure()
        run: |
          curl -H 'Content-Type: application/json' -d '{
            "title": "❌ CD Pipeline",
            "text": "Falha no pipeline de CD. Verificar logs no GitHub Actions."
          }' $TEAMS_WEBHOOK_URL
        displayName: '📣 Notificar Teams (falha)'
