trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: continuous_delivery
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'
      displayName: 'Usando python 3.8'
    - script: |
        echo "{}" > ~/.databricks-connect
      displayName: 'Databricks config'
    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt wheel twine
      displayName: 'Installing libraries'
    - script: |
        python setup.py bdist_wheel
      displayName: 'Building package'
    - task: TwineAuthenticate@1
      inputs:
        artifactFeed: 'python_library_teste'
      displayName: 'Authenticating to Feed'
    - script: |
        twine upload -r "python_library_teste" --config-file $(PYPIRC_PATH) dist/*
      displayName: 'Uploading package'