name: CI Bundle Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'resources/pipelines/lakehouse_pipeline.yml'  # Só dispara se esse arquivo mudar

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Databricks CLI
        run: pip install databricks-cli

      - name: Configure Databricks CLI
        run: databricks auth login --host ${{ secrets.DATABRICKS_HOST }} --token ${{ secrets.DATABRICKS_TOKEN }}

      - name: Validate Bundle
        run: databricks bundle validate

      - name: Deploy Bundle
        run: databricks bundle deploy --target dev

      - name: Run Lakehouse Pipeline
        run: databricks bundle run iris_pipeline --target dev
