resources:
  jobs:
    training_job:
      name: iris_model_training
      tasks:
        - task_key: train_model
          depends_on:
            - task_key: transform_silver  # tarefa do silver_job
          description: "Treina o modelo com MLflow e registra no UC"
          notebook_task:
            notebook_path: notebooks/04_train_model.py
            base_parameters:
              input_gold_table: ${bundle.configuration.output_gold_table}
              output_model: ${bundle.configuration.output_model}
          existing_cluster_id: ${bundle.configuration.cluster_id}
