resources:
  jobs:
    training_job:
      name: iris_model_training
      tasks:
        - task_key: train_model
          description: "Treina o modelo com MLflow e registra no UC"
          notebook_task:
            notebook_path: /Workspace/Users/xultezz@gmail.com/.bundle/iris_bundle/dev/files/notebooks/04_train_model
            base_parameters:
              input_gold_table: ${var.output_silver_table}  # Use Silver data for ML training
              output_model: ${var.output_model}
