resources:
  jobs:
    training_job:
      name: iris_model_training
      tags:
        layer: "ml"
        project: "iris_pipeline"
        trigger_order: "3b"
        triggered_by: "silver_job"
      tasks:
        - task_key: train_model
          description: "Treinamento de modelo ML com registro no MLflow"
          notebook_task:
            notebook_path: ${workspace.file_path}/notebooks/04_train_model
            base_parameters:
              input_table: ${var.catalog_name}.${var.schema_name}.iris_silver
              model_name: iris_classifier
              stage: "Production"
          timeout_seconds: 1800
          max_retries: 2
